### ISSUE TITLE
Implemeting pontuation

### ISSUE THREAD

**Issue by emanuelgsouza** [emanuelgsouza/debated3d-site#33]
Dar uma olhada: https://docs.google.com/document/d/1jw157PlLg0LeVYhjr89I8N1Za1AwtvfDvKgVeNg8AVU/edit

**Comment by AlanCosta7** [comment]
Sistema de jogo:
Página de Ranking dos Usuários
**Usuário FREE:**
Criar CARD = 10 pontos
Votar no tema = 5 pontos
Votar no CARD = 1 ponto
**Usuário PRO:**
Criar CARD = 10 pontos
Votar no tema = 5 pontos
Votar no CARD = 1 ponto
Votos no meu TEMA = 1 ponto por voto
CARDs criados no meu TEMA = 5 pontos por CARD
